### ISSUE TITLE
Server crash on Test branch

### ISSUE THREAD

**Issue by w1lla** [maniaplanet/game-modes-mp3#2]
Server crash:

[2013/09/09 19:45:26] Script compilation failed: ERROR[Modes/ShootMania/ModeSports.Script.txt : 2137, 39] Function Disable not found
ERROR[Modes/ShootMania/ModeSports.Script.txt : 2138, 39] Function Disable not found
ERROR[Modes/ShootMania/ModeSports.Script.txt : 2157, 10] Function Enable not found
ERROR[Modes/ShootMania/ModeSports.Script.txt : 2158, 10] Function Enable not found
Script compilation failed.

No WarmUp2.Script.txt has no function for that.

**Comment by Aessi** [comment]
The missing functions were added to the WarmUp2 library.
e22a607634820af40528ceb6f01ae545788ed650
