### ISSUE TITLE
Some small issues

### ISSUE THREAD

**Issue by kremsy** [maniaplanet/game-modes-mp3#3]
The Extend Warmup Callback is reacting a bit weired, if a warmup is in progress and the counter counts down, you extend nothing happens, if the warmup get stopped (by an f6 of a player) you see that the time got increase by the extending value.

But in fact it should be if the warmup counts down (timer is at 30s) you extend by 10 second it should go directly to 40 and keeps continuisly to be counted down.

It would be also very importnt if there could be a command to ask if the warmup commands are available in this mode (to build buttons in a menu dynamically for example, and not display them in all modes which dont support that option).

Another very very very important thing would be that the disableScoreboadOnAlt should also work while warmup stages ;).

**Comment by Aessi** [comment]
In the next update:
- Warmup_Extend Callback fixed
- Addition of a new method and callback to know if the mode use a WarmUp
- The LibXmlRpc_DisableAltMenu/LibXmlRpc_EnableAltMenu callbacks work during the warm up
