### ISSUE TITLE
ModeSport S_Mode assert

### ISSUE THREAD

**Issue by steeffeen-zz** [maniaplanet/game-modes-mp3#4]
[2014/06/21 13:16:28] Script 'Mode:Elite' halted: [Modes/ShootMania/ModeSport.Script.txt : 177, 34][Called from : 75, 31] Assertion failed

one of our servers started over and over again because someone changed the match setting S_Mode to 99
the controller saved the settings and since a normal restart the server didn't work anymore

i think it would make more sense to replace assert()s by log message and using a default value instead of the settings

**Comment by Aessi** [comment]
It will be fixed in the next update. The script will use a GetMode() function instead of using the value of S_Mode directly. The function will always return a valid value and the assert() will be removed.
