### ISSUE TITLE
Map Elite Shootmania - Issue at launch

### ISSUE THREAD

**Issue by choosetwo** [maniaplanet/game-modes-mp3#9]
Hello, 

I have created a elite  map on shootmania, Actually the map is validated and when I try to start playing in local I have an error message : 

_This script requires an excution context of type CSmEditorPluginMapType but was compiled in
context of CSmArnaRulesMode_

I Use this script "EliteArena.Script.txt"
What should I do ? 

Thanks by advance,

_WkY_ SuperMurloc

**Comment by Aessi** [comment]
Are you launching a local server inside the Elite title pack or inside of the Storm title pack? 
To launch the game mode in local you have to use the **Elite.Script.txt** file. **EliteArena.Script.txt** is only used to validate the map.

**Comment by choosetwo** [comment]
Hi Thanks for your answer,
I am launching  inside oh the storm title pack. I will test that and let you know. 
Thanks

**Comment by Aessi** [comment]
If you're creating an Elite map, then it's recommended to do it inside the Elite title pack. There you will have everything you need to do so. If you do it inside the Storm title pack you have to download all Elite related scripts to get everything working.

**Comment by choosetwo** [comment]
Right ! 
Everything works fine now, 

Thanks a lot !
